

if __name__ == '__main__':

    fichier=open('dossier_filleuil','w')
    fichier.write("AKORA SIALOU MARIAM FATIM\n")
    fichier.write("ATTEKE WILFRIED ANDERSON\n")
    fichier.write("CAMARA IBRAHIM\n")
    fichier.write("DIOMANDE DAOUDA\n")
    fichier.write("FOFANAN MAWA\n")
    fichier.write("GUEU MEANGO DIEUMAN HERMANN\n")
    fichier.write("KAMBOU SIE MARDOCHEE\n")
    fichier.write("KANON CHRISTIAN JOEL\n")
    fichier.write("KESSE BEDJA BORIS\n")
    fichier.write("KOFFI HERMANN KEVIN KOUAME\n")
    fichier.write("KOFFIYAO ERIC JOEL\n")
    fichier.write("KONATE ISSA MAURY CHEICK JUNIOR\n")
    fichier.write("KONDE MHANT BEN MAMADOU\n")
    fichier.write("KOUADIO YOBOUET JACQUES\n")
    fichier.write("KOUAKOU KONAN VIVIEN\n")
    fichier.write("LOUKOU GUY LANDRY\n")
    fichier.write("MAHI AKOH JEANNOT DOMINIQUE\n")
    fichier.write("N'GUESSAN KOUAME RODRIGUE\n")
    fichier.write("N'GUESSAN N'GUESSAN RODRIGUE\n")
    fichier.write("SORO KIDJOUFOLO FATIM ARMEL\n")
    fichier.write("SORO WONNAN\n")
    fichier.write("TUO IBRAHIM TIOVIGUE\n")
    fichier.write("YAO LASME LINDAY MIRELLA\n")
    fichier.write("YAO VANESSA AMANI DE-FALLEY\n")
    fichier.write("YEO FOUNIGNIGUE CLEMENT\n")
    fichier.close()
